.TH VCMAILBOX 1
.
.SH NAME
vcmailbox \- send messages to the VideoCore via the mailbox
.
.
.SH SYNOPSIS
.SY vcmailbox
.RI [ word0 ]
.RI [ word1 ]
\|.\|.\|.
.
.
.SH DESCRIPTION
.B vcmailbox
is a low-level utility for sending mailbox messages to the VideoCore. See
.B [MAILBOX]
or
.BR vcmailbox (7)
for more information on the available messages and their respective formats.
and
.BR raspiotp (7)
for some examples of typical usage.
.
.
.SH SEE ALSO
.BR vcgencmd (1),
.BR raspiotp (7),
.B [MAILBOX]
.
.
.SH REFERENCES
.TP
.B [MAILBOX]
https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface
